/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Eventos;

import java.awt.Color;
import java.awt.Container;
import java.awt.Font;
import java.text.ParseException;
import javax.swing.BorderFactory;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Tem
 */
public class ExrEvento extends javax.swing.JFrame {

    /**
     * Creates new form ExrEvento
     */
    public ExrEvento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFormulario = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        jtfCodigo = new javax.swing.JTextField();
        lblApelido = new javax.swing.JLabel();
        jtfApelido = new javax.swing.JTextField();
        lblNomeComp = new javax.swing.JLabel();
        jtfNomeComp = new javax.swing.JTextField();
        lblDataNascimento = new javax.swing.JLabel();
        jtfDataNascimento = new javax.swing.JTextField();
        lblNrBI = new javax.swing.JLabel();
        jtfNrBI = new javax.swing.JTextField();
        lblSexo = new javax.swing.JLabel();
        jcbSexo = new javax.swing.JComboBox<>();
        lblEstSivil = new javax.swing.JLabel();
        jcbEstCivil = new javax.swing.JComboBox<>();
        lblContatos = new javax.swing.JLabel();
        jtfContatos = new javax.swing.JTextField();
        lblNaturalidade = new javax.swing.JLabel();
        jtfNaturalidade = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        jtfEmail = new javax.swing.JTextField();
        lblEndereco = new javax.swing.JLabel();
        jtfEndereco = new javax.swing.JTextField();
        lblSalario = new javax.swing.JLabel();
        jtfalario = new javax.swing.JTextField();
        lblObservacao = new javax.swing.JLabel();
        jtfObservacao = new javax.swing.JTextField();
        jbtSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registo De Funcionario");

        lblFormulario.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblFormulario.setText("FORMULARIO PARA REGISRO DE UM FUNCIONARIO");

        lblCodigo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblCodigo.setText("Codigo");
        lblCodigo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCodigoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCodigoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblCodigoMousePressed(evt);
            }
        });

        jtfCodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfCodigoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfCodigoFocusLost(evt);
            }
        });
        jtfCodigo.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jtfCodigoInputMethodTextChanged(evt);
            }
        });
        jtfCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCodigoActionPerformed(evt);
            }
        });
        jtfCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfCodigoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfCodigoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfCodigoKeyTyped(evt);
            }
        });

        lblApelido.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblApelido.setText("Apelido");
        lblApelido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblApelidoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblApelidoMouseExited(evt);
            }
        });
        lblApelido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lblApelidoKeyTyped(evt);
            }
        });

        jtfApelido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfApelidoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfApelidoFocusLost(evt);
            }
        });
        jtfApelido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfApelidoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfApelidoKeyTyped(evt);
            }
        });

        lblNomeComp.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblNomeComp.setText("Nome Comp.");
        lblNomeComp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblNomeCompMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblNomeCompMouseExited(evt);
            }
        });

        jtfNomeComp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfNomeCompFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfNomeCompFocusLost(evt);
            }
        });
        jtfNomeComp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfNomeCompKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfNomeCompKeyTyped(evt);
            }
        });

        lblDataNascimento.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblDataNascimento.setText("Data Nasc.");
        lblDataNascimento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblDataNascimentoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblDataNascimentoMouseExited(evt);
            }
        });

        jtfDataNascimento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfDataNascimentoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfDataNascimentoFocusLost(evt);
            }
        });
        jtfDataNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfDataNascimentoActionPerformed(evt);
            }
        });
        jtfDataNascimento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfDataNascimentoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfDataNascimentoKeyTyped(evt);
            }
        });

        lblNrBI.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblNrBI.setText("Nr De BI");
        lblNrBI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblNrBIMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblNrBIMouseExited(evt);
            }
        });

        jtfNrBI.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfNrBIFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfNrBIFocusLost(evt);
            }
        });
        jtfNrBI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfNrBIKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfNrBIKeyTyped(evt);
            }
        });

        lblSexo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblSexo.setText("Sexo");
        lblSexo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSexoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSexoMouseExited(evt);
            }
        });

        jcbSexo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jcbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Masculino", "Feminino" }));
        jcbSexo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcbSexoKeyPressed(evt);
            }
        });

        lblEstSivil.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblEstSivil.setText("Est. civil");
        lblEstSivil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblEstSivilMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblEstSivilMouseExited(evt);
            }
        });

        jcbEstCivil.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jcbEstCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Solteirro", "Casado" }));
        jcbEstCivil.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcbEstCivilKeyPressed(evt);
            }
        });

        lblContatos.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblContatos.setText("Contatos");
        lblContatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblContatosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblContatosMouseExited(evt);
            }
        });

        jtfContatos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfContatosFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfContatosFocusLost(evt);
            }
        });
        jtfContatos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfContatosKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfContatosKeyTyped(evt);
            }
        });

        lblNaturalidade.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblNaturalidade.setText("Naturalidade");
        lblNaturalidade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblNaturalidadeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblNaturalidadeMouseExited(evt);
            }
        });

        jtfNaturalidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfNaturalidadeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfNaturalidadeFocusLost(evt);
            }
        });
        jtfNaturalidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfNaturalidadeKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfNaturalidadeKeyTyped(evt);
            }
        });

        lblEmail.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblEmail.setText("E-mail");
        lblEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblEmailMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblEmailMouseExited(evt);
            }
        });
        lblEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lblEmailKeyTyped(evt);
            }
        });

        jtfEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfEmailFocusLost(evt);
            }
        });
        jtfEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfEmailKeyPressed(evt);
            }
        });

        lblEndereco.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblEndereco.setText("Endereco");
        lblEndereco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblEnderecoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblEnderecoMouseExited(evt);
            }
        });

        jtfEndereco.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfEnderecoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfEnderecoFocusLost(evt);
            }
        });
        jtfEndereco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfEnderecoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfEnderecoKeyTyped(evt);
            }
        });

        lblSalario.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblSalario.setText("Salario");
        lblSalario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSalarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSalarioMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblSalarioMousePressed(evt);
            }
        });
        lblSalario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lblSalarioKeyTyped(evt);
            }
        });

        jtfalario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfalarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfalarioFocusLost(evt);
            }
        });
        jtfalario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfalarioKeyPressed(evt);
            }
        });

        lblObservacao.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblObservacao.setText("Observacao");
        lblObservacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblObservacaoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblObservacaoMouseExited(evt);
            }
        });
        lblObservacao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lblObservacaoKeyTyped(evt);
            }
        });

        jtfObservacao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfObservacaoKeyPressed(evt);
            }
        });

        jbtSalvar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jbtSalvar.setText("Salvar");
        jbtSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSalvarActionPerformed(evt);
            }
        });
        jbtSalvar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtSalvarKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEndereco)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, 709, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblNomeComp)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(lblCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblApelido, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))
                                            .addComponent(lblDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblNrBI, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtfApelido, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtfNomeComp, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtfDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jtfEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                                                .addComponent(jtfContatos, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jtfNrBI, javax.swing.GroupLayout.Alignment.LEADING))))
                                    .addComponent(lblContatos, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(220, 220, 220)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblNaturalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jtfNaturalidade))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(58, 58, 58)
                                        .addComponent(jtfalario))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblSexo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblEstSivil, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE))
                                        .addGap(49, 49, 49)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jcbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jcbEstCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(lblObservacao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(30, 30, 30)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtfEmail)
                                            .addComponent(jtfObservacao))))))
                        .addGap(68, 68, 68))))
            .addGroup(layout.createSequentialGroup()
                .addGap(413, 413, 413)
                .addComponent(jbtSalvar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblFormulario)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigo)
                    .addComponent(jtfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSexo)
                    .addComponent(jcbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApelido)
                    .addComponent(jtfApelido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEstSivil)
                    .addComponent(jcbEstCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfNomeComp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNomeComp)
                    .addComponent(lblNaturalidade)
                    .addComponent(jtfNaturalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataNascimento)
                    .addComponent(jtfDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmail)
                    .addComponent(jtfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNrBI)
                    .addComponent(jtfNrBI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSalario)
                    .addComponent(jtfalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContatos)
                    .addComponent(jtfContatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblObservacao)
                    .addComponent(jtfObservacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEndereco)
                    .addComponent(jtfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jbtSalvar)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtfDataNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfDataNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfDataNascimentoActionPerformed

    private void jtfCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCodigoActionPerformed

    private void jtfCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCodigoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();

        }
    }//GEN-LAST:event_jtfCodigoKeyTyped

    private void jtfCodigoInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jtfCodigoInputMethodTextChanged
    }//GEN-LAST:event_jtfCodigoInputMethodTextChanged

    private void lblCodigoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCodigoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCodigoMousePressed

    private void jtfCodigoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfCodigoFocusGained

        if (jtfCodigo.getText().equals("ex: 1234")) {
            jtfCodigo.setText("");
        }
    }//GEN-LAST:event_jtfCodigoFocusGained

    private void jtfCodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCodigoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jtfApelido.requestFocus();

            if (evt.getKeyCode() == evt.VK_ENTER) {
            }
        }
    }//GEN-LAST:event_jtfCodigoKeyPressed

    private void jtfApelidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfApelidoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jtfNomeComp.requestFocus();
            if (evt.getKeyCode() == evt.VK_ENTER) {
            }
        }
    }//GEN-LAST:event_jtfApelidoKeyPressed

    private void jtfNomeCompKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNomeCompKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jtfDataNascimento.requestFocus();
            if (evt.getKeyCode() == evt.VK_ENTER) {
            }
        }
    }//GEN-LAST:event_jtfNomeCompKeyPressed

    private void jtfDataNascimentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfDataNascimentoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jtfNrBI.requestFocus();
            if (evt.getKeyCode() == evt.VK_ENTER) {
            }
        }
    }//GEN-LAST:event_jtfDataNascimentoKeyPressed

    private void jtfNrBIKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNrBIKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jtfContatos.requestFocus();
            if (evt.getKeyCode() == evt.VK_ENTER) {
            }
        }
    }//GEN-LAST:event_jtfNrBIKeyPressed

    private void jtfContatosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfContatosKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jtfEndereco.requestFocus();
            if (evt.getKeyCode() == evt.VK_ENTER) {
            }
        } else if (evt.getKeyCode() == evt.VK_0) {
            jtfContatos.getText();
            if (evt.getKeyCode() == evt.VK_0) {
            }
        }
    }//GEN-LAST:event_jtfContatosKeyPressed

    private void jtfEnderecoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfEnderecoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jcbSexo.requestFocus();
            if (evt.getKeyCode() == evt.VK_ENTER) {
            }
        }
    }//GEN-LAST:event_jtfEnderecoKeyPressed

    private void jcbSexoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcbSexoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jcbEstCivil.requestFocus();
            if (evt.getKeyCode() == evt.VK_ENTER) {
            }
        }
    }//GEN-LAST:event_jcbSexoKeyPressed

    private void jcbEstCivilKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcbEstCivilKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jtfNaturalidade.requestFocus();
            if (evt.getKeyCode() == evt.VK_ENTER) {
            }
        }
    }//GEN-LAST:event_jcbEstCivilKeyPressed

    private void jtfNaturalidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNaturalidadeKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jtfEmail.requestFocus();
            if (evt.getKeyCode() == evt.VK_ENTER) {
            }
        }
    }//GEN-LAST:event_jtfNaturalidadeKeyPressed

    private void jtfEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfEmailKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jtfalario.requestFocus();
            if (evt.getKeyCode() == evt.VK_ENTER) {
            }
        }
    }//GEN-LAST:event_jtfEmailKeyPressed

    private void jtfalarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfalarioKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jtfObservacao.requestFocus();
            if (evt.getKeyCode() == evt.VK_ENTER) {
            }
        }
    }//GEN-LAST:event_jtfalarioKeyPressed

    private void jtfObservacaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfObservacaoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jbtSalvar.requestFocus();
            if (evt.getKeyCode() == evt.VK_ENTER) {
            }
        }
    }//GEN-LAST:event_jtfObservacaoKeyPressed

    private void jbtSalvarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtSalvarKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jtfCodigo.requestFocus();
            if (evt.getKeyCode() == evt.VK_ENTER) {
            }
        }
    }//GEN-LAST:event_jbtSalvarKeyPressed

    private void jtfCodigoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCodigoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCodigoKeyReleased

    private void lblCodigoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCodigoMouseEntered
        // TODO add your handling code here:
        lblCodigo.setFont(new Font(String.valueOf(getFont()), Font.PLAIN, 22));

    }//GEN-LAST:event_lblCodigoMouseEntered

    private void lblApelidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblApelidoKeyTyped
        // TODO add your handling code here:
        char vali = evt.getKeyChar();
        if (Character.isDigit(vali)) {
            getToolkit().beep();
            evt.consume();

        }
    }//GEN-LAST:event_lblApelidoKeyTyped

    private void jtfNomeCompKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNomeCompKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jtfNomeCompKeyTyped

    private void jtfNaturalidadeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNaturalidadeKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jtfNaturalidadeKeyTyped

    private void lblApelidoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblApelidoMouseEntered
        // TODO add your handling code here:
        lblApelido.setFont(new Font(String.valueOf(getFont()), Font.PLAIN, 22));
    }//GEN-LAST:event_lblApelidoMouseEntered

    private void lblNomeCompMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNomeCompMouseEntered
        // TODO add your handling code here:
        lblNomeComp.setFont(new Font(String.valueOf(getFont()), Font.PLAIN, 22));

    }//GEN-LAST:event_lblNomeCompMouseEntered

    private void lblDataNascimentoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDataNascimentoMouseEntered
        // TODO add your handling code here:
        lblDataNascimento.setFont(new Font(String.valueOf(getFont()), Font.PLAIN, 22));
    }//GEN-LAST:event_lblDataNascimentoMouseEntered

    private void lblNrBIMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNrBIMouseEntered
        // TODO add your handling code here:
        lblNrBI.setFont(new Font(String.valueOf(getFont()), Font.PLAIN, 22));
    }//GEN-LAST:event_lblNrBIMouseEntered

    private void lblContatosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblContatosMouseEntered
        // TODO add your handling code here:
        lblContatos.setFont(new Font(String.valueOf(getFont()), Font.PLAIN, 22));
    }//GEN-LAST:event_lblContatosMouseEntered

    private void lblEnderecoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEnderecoMouseEntered
        // TODO add your handling code here:
        lblEndereco.setFont(new Font(String.valueOf(getFont()), Font.PLAIN, 22));
    }//GEN-LAST:event_lblEnderecoMouseEntered

    private void lblSexoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSexoMouseEntered
        // TODO add your handling code here:
        lblSexo.setFont(new Font(String.valueOf(getFont()), Font.PLAIN, 22));
    }//GEN-LAST:event_lblSexoMouseEntered

    private void lblEstSivilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEstSivilMouseEntered
        // TODO add your handling code here:
        lblEstSivil.setFont(new Font(String.valueOf(getFont()), Font.PLAIN, 22));
    }//GEN-LAST:event_lblEstSivilMouseEntered

    private void lblNaturalidadeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNaturalidadeMouseEntered
        // TODO add your handling code here:
        lblNaturalidade.setFont(new Font(String.valueOf(getFont()), Font.PLAIN, 22));
    }//GEN-LAST:event_lblNaturalidadeMouseEntered

    private void lblEmailMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEmailMouseEntered
        // TODO add your handling code here:
        lblEmail.setFont(new Font(String.valueOf(getFont()), Font.PLAIN, 22));
    }//GEN-LAST:event_lblEmailMouseEntered

    private void lblSalarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalarioMouseEntered
        // TODO add your handling code here:
        lblSalario.setFont(new Font(String.valueOf(getFont()), Font.PLAIN, 22));
    }//GEN-LAST:event_lblSalarioMouseEntered

    private void lblObservacaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblObservacaoMouseEntered
        // TODO add your handling code here:
        lblObservacao.setFont(new Font(String.valueOf(getFont()), Font.PLAIN, 22));
    }//GEN-LAST:event_lblObservacaoMouseEntered

    private void lblCodigoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCodigoMouseExited
        // TODO add your handling code here:
        lblCodigo.setFont(new Font(String.valueOf("Times New Roman"), Font.BOLD, 18));
    }//GEN-LAST:event_lblCodigoMouseExited

    private void lblApelidoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblApelidoMouseExited
        // TODO add your handling code here:
        lblApelido.setFont(new Font(String.valueOf("Times New Roman"), Font.BOLD, 18));
    }//GEN-LAST:event_lblApelidoMouseExited

    private void lblNomeCompMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNomeCompMouseExited
        // TODO add your handling code here:
        lblNomeComp.setFont(new Font(String.valueOf("Times New Roman"), Font.BOLD, 18));
    }//GEN-LAST:event_lblNomeCompMouseExited

    private void lblDataNascimentoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDataNascimentoMouseExited
        // TODO add your handling code here:
        lblDataNascimento.setFont(new Font(String.valueOf("Times New Roman"), Font.BOLD, 18));
    }//GEN-LAST:event_lblDataNascimentoMouseExited

    private void lblNrBIMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNrBIMouseExited
        // TODO add your handling code here:
        lblNrBI.setFont(new Font(String.valueOf("Times New Roman"), Font.BOLD, 18));
    }//GEN-LAST:event_lblNrBIMouseExited

    private void lblContatosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblContatosMouseExited
        // TODO add your handling code here:
        lblContatos.setFont(new Font(String.valueOf("Times New Roman"), Font.BOLD, 18));
    }//GEN-LAST:event_lblContatosMouseExited

    private void lblEnderecoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEnderecoMouseExited
        // TODO add your handling code here:
        lblEndereco.setFont(new Font(String.valueOf("Times New Roman"), Font.BOLD, 18));
    }//GEN-LAST:event_lblEnderecoMouseExited

    private void lblSexoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSexoMouseExited
        // TODO add your handling code here:
        lblSexo.setFont(new Font(String.valueOf("Times New Roman"), Font.BOLD, 18));

    }//GEN-LAST:event_lblSexoMouseExited

    private void lblEstSivilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEstSivilMouseExited
        // TODO add your handling code here:
        lblEstSivil.setFont(new Font(String.valueOf("Times New Roman"), Font.BOLD, 18));
    }//GEN-LAST:event_lblEstSivilMouseExited

    private void lblNaturalidadeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNaturalidadeMouseExited
        // TODO add your handling code here:
        lblNaturalidade.setFont(new Font(String.valueOf("Times New Roman"), Font.BOLD, 18));
    }//GEN-LAST:event_lblNaturalidadeMouseExited

    private void lblEmailMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEmailMouseExited
        // TODO add your handling code here:
        lblEmail.setFont(new Font(String.valueOf("Times New Roman"), Font.BOLD, 18));
    }//GEN-LAST:event_lblEmailMouseExited

    private void lblSalarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalarioMousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_lblSalarioMousePressed

    private void lblSalarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalarioMouseExited
        // TODO add your handling code here:
        lblSalario.setFont(new Font(String.valueOf("Times New Roman"), Font.BOLD, 18));
    }//GEN-LAST:event_lblSalarioMouseExited

    private void lblObservacaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblObservacaoMouseExited
        // TODO add your handling code here:
        lblObservacao.setFont(new Font(String.valueOf("Times New Roman"), Font.BOLD, 18));
    }//GEN-LAST:event_lblObservacaoMouseExited

    private void jtfCodigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfCodigoFocusLost
        // TODO add your handling code here:
        perderFoco(jtfCodigo, "ex: 1234");
    }//GEN-LAST:event_jtfCodigoFocusLost

    private void jtfApelidoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfApelidoFocusLost
        // TODO add your handling code here:
        perderFoco(jtfApelido, "ex: Tembe");
    }//GEN-LAST:event_jtfApelidoFocusLost

    private void jtfApelidoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfApelidoFocusGained
        // TODO add your handling code here:
        ganharFocus(jtfApelido, "ex: Tembe");
    }//GEN-LAST:event_jtfApelidoFocusGained

    private void jtfNomeCompFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfNomeCompFocusGained
        // TODO add your handling code here:
        ganharFocus(jtfNomeComp, "ex: Antonio Zeferino");
    }//GEN-LAST:event_jtfNomeCompFocusGained

    private void jtfNomeCompFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfNomeCompFocusLost
        // TODO add your handling code here:
        perderFoco(jtfNomeComp, "ex: Antonio Zeferino");
    }//GEN-LAST:event_jtfNomeCompFocusLost

    private void jtfDataNascimentoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfDataNascimentoFocusGained
        // TODO add your handling code here:
        ganharFocus(jtfDataNascimento, "ex: 01/10/1999");
    }//GEN-LAST:event_jtfDataNascimentoFocusGained

    private void jtfDataNascimentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfDataNascimentoFocusLost
        // TODO add your handling code here:
        perderFoco(jtfDataNascimento, "ex: 01/10/1999");
    }//GEN-LAST:event_jtfDataNascimentoFocusLost

    private void jtfNrBIFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfNrBIFocusGained
        // TODO add your handling code here:
        ganharFocus(jtfNrBI, "ex: 110202341587F");
    }//GEN-LAST:event_jtfNrBIFocusGained

    private void jtfNrBIFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfNrBIFocusLost
        // TODO add your handling code here:
        perderFoco(jtfNrBI, "ex: 110202341587F");
    }//GEN-LAST:event_jtfNrBIFocusLost

    private void jtfContatosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfContatosFocusGained
        // TODO add your handling code here:
        ganharFocus(jtfContatos, "ex: 843921823");
    }//GEN-LAST:event_jtfContatosFocusGained

    private void jtfContatosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfContatosFocusLost
        // TODO add your handling code here:
        perderFoco(jtfContatos, "ex: 843921823");
    }//GEN-LAST:event_jtfContatosFocusLost

    private void jtfEnderecoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfEnderecoFocusGained
        // TODO add your handling code here:
        ganharFocus(jtfEndereco, "ex: Zona Verde ");
    }//GEN-LAST:event_jtfEnderecoFocusGained

    private void jtfEnderecoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfEnderecoFocusLost
        // TODO add your handling code here:
        perderFoco(jtfEndereco, "ex: Zona Verde ");
    }//GEN-LAST:event_jtfEnderecoFocusLost

    private void jtfNaturalidadeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfNaturalidadeFocusGained
        // TODO add your handling code here:
        ganharFocus(jtfNaturalidade, "ex: Maputo");
    }//GEN-LAST:event_jtfNaturalidadeFocusGained

    private void jtfNaturalidadeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfNaturalidadeFocusLost
        // TODO add your handling code here:
        perderFoco(jtfNaturalidade, "ex: Maputo");
    }//GEN-LAST:event_jtfNaturalidadeFocusLost

    private void jtfEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfEmailFocusGained
        // TODO add your handling code here:
        ganharFocus(jtfEmail, "ex: antoniotembe00@gmail.com");
    }//GEN-LAST:event_jtfEmailFocusGained

    private void jtfEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfEmailFocusLost
        // TODO add your handling code here:
        perderFoco(jtfEmail, "ex: antoniotembe00@gmail.com");
    }//GEN-LAST:event_jtfEmailFocusLost

    private void jtfalarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfalarioFocusGained
        // TODO add your handling code here:
        ganharFocus(jtfalario, "25000");
    }//GEN-LAST:event_jtfalarioFocusGained

    private void jtfalarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfalarioFocusLost
        // TODO add your handling code here
        perderFoco(jtfalario, "25000");
    }//GEN-LAST:event_jtfalarioFocusLost

    private void jtfApelidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfApelidoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jtfApelidoKeyTyped

    private void jtfDataNascimentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfDataNascimentoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) || (evt.getKeyCode() == evt.VK_DIVIDE)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jtfDataNascimentoKeyTyped

    private void jtfNrBIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNrBIKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNrBIKeyTyped

    private void jtfContatosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfContatosKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jtfContatosKeyTyped

    private void jtfEnderecoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfEnderecoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jtfEnderecoKeyTyped

    private void lblEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblEmailKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if ((Character.isDigit(c)) || (evt.getKeyCode() == evt.VK_AT)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_lblEmailKeyTyped

    private void lblSalarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblSalarioKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }

    }//GEN-LAST:event_lblSalarioKeyTyped

    private void lblObservacaoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblObservacaoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_lblObservacaoKeyTyped

    private void jbtSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSalvarActionPerformed
        // TODO add your handling code here:
        if (jtfCodigo.getText().equals("")) {
            jtfCodigo.setBorder(BorderFactory.createLineBorder(Color.red));
            jtfCodigo.requestFocus();
            JOptionPane.showMessageDialog(null, "Prencha os Campos Vazios");
        } else if (jtfNomeComp.getText().equals("")) {
            jtfNomeComp.setBorder(BorderFactory.createLineBorder(Color.red));
            jtfNomeComp.requestFocus();
            JOptionPane.showMessageDialog(null, "Prencha os Campos Vazios");

        } else if (jtfApelido.getText().equals("")) {
            jtfApelido.setBorder(BorderFactory.createLineBorder(Color.red));
            jtfApelido.requestFocus();
            JOptionPane.showMessageDialog(null, "Prencha os Campos Vazios");

        } else if (jtfNrBI.getText().equals("")) {
            jtfNrBI.setBackground(Color.red);
            jtfNrBI.setBorder(BorderFactory.createLineBorder(Color.red));
            JOptionPane.showMessageDialog(null, "Prencha os Campos Vazios");

        } else if (jtfDataNascimento.getText().equals("")) {
            jtfDataNascimento.setBackground(Color.red);
            jtfDataNascimento.setBorder(BorderFactory.createLineBorder(Color.red));
            JOptionPane.showMessageDialog(null, "Prencha os Campos Vazios");
            
        } else if (jtfNaturalidade.getText().equals("")) {
            jtfNaturalidade.setBorder(BorderFactory.createLineBorder(Color.red));
            jtfNaturalidade.requestFocus();
            JOptionPane.showMessageDialog(null, "Prencha os Campos Vazios");

        } else if (jtfEndereco.getText().equals("")) {
            jtfEndereco.setBackground(Color.red);
            jtfEndereco.setBorder(BorderFactory.createLineBorder(Color.red));
            JOptionPane.showMessageDialog(null, "Prencha os Campos Vazios");
            
        } else if (jtfalario.getText().equals("")) {
            jtfalario.setBackground(Color.red);
            jtfalario.setBorder(BorderFactory.createLineBorder(Color.red));
            JOptionPane.showMessageDialog(null, "Prencha os Campos Vazios");
        
        }else if (jtfObservacao.getText().equals("")) {
            jtfObservacao.setBackground(Color.red);
            jtfObservacao.setBorder(BorderFactory.createLineBorder(Color.red));
            JOptionPane.showMessageDialog(null, "Prencha os Campos Vazios");
        
        }else if (jtfEmail.getText().equals("")) {
            jtfEmail.setBorder(BorderFactory.createLineBorder(Color.red));
            jtfEmail.requestFocus();
            JOptionPane.showMessageDialog(null, "Prencha os Campos Vazios");

        } else if (jtfContatos.getText().equals("")) {
            jtfContatos.setBorder(BorderFactory.createLineBorder(Color.red));
            jtfContatos.requestFocus();
            JOptionPane.showMessageDialog(null, "Prencha os Campos Vazios");

        } else if (jcbSexo.getItemListeners().equals("")) {
            jcbSexo.setBackground(Color.red);
            jcbSexo.setBorder(BorderFactory.createLineBorder(Color.red));
            JOptionPane.showMessageDialog(null, "Prencha os Campos Vazios");
        
        }else if (jcbEstCivil.getItemListeners().equals("")) {
            jcbEstCivil.setBackground(Color.red);
            jcbSexo.setBorder(BorderFactory.createLineBorder(Color.red));
            JOptionPane.showMessageDialog(null, "Prencha os Campos Vazios");
        }  else {
            JOptionPane.showMessageDialog(this, "Obrigado por Prencher todos os Campos");
        }
    }//GEN-LAST:event_jbtSalvarActionPerformed

    private void ganharFocus(JTextField tf, String s) {
        if (tf.getText().equals(s)) {
            tf.setText("");
            // tf.setBackground(Color.white);
        } //To change body of generated methods, choose Tools | Templates.
    }

    private void perderFoco(JTextField tf, String s) {
        if (tf.getText().equals("")) {
            tf.setText(s);
            //tf.setBackground(Color.white);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExrEvento().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtSalvar;
    private javax.swing.JComboBox<String> jcbEstCivil;
    private javax.swing.JComboBox<String> jcbSexo;
    private javax.swing.JTextField jtfApelido;
    private javax.swing.JTextField jtfCodigo;
    private javax.swing.JTextField jtfContatos;
    private javax.swing.JTextField jtfDataNascimento;
    private javax.swing.JTextField jtfEmail;
    private javax.swing.JTextField jtfEndereco;
    private javax.swing.JTextField jtfNaturalidade;
    private javax.swing.JTextField jtfNomeComp;
    private javax.swing.JTextField jtfNrBI;
    private javax.swing.JTextField jtfObservacao;
    private javax.swing.JTextField jtfalario;
    private javax.swing.JLabel lblApelido;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblContatos;
    private javax.swing.JLabel lblDataNascimento;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblEstSivil;
    private javax.swing.JLabel lblFormulario;
    private javax.swing.JLabel lblNaturalidade;
    private javax.swing.JLabel lblNomeComp;
    private javax.swing.JLabel lblNrBI;
    private javax.swing.JLabel lblObservacao;
    private javax.swing.JLabel lblSalario;
    private javax.swing.JLabel lblSexo;
    // End of variables declaration//GEN-END:variables
}
